- name: ansible
  hosts: localhost
  become: true
  vars:
    COURSE: "devops"
    VALUE: "four"
  tasks:
  - name: task-1
    ansible.builtin.debug:
      msg: "hi this is {{COURSE}}, duration is {{VALUE}} months"