- name: ansible
  hosts: localhost
  become: true
  tasks:
  - name: task-1
    vars:
      COURSE: "devops"
      VALUE: "four"
    ansible.builtin.debug:
      msg: "hi am learning  {{COURSE}}, duration is {{VALUE}} months"