- name: ansible
  hosts: localhost
  become: true
  vars_prompt:
    - name: COURSE
      prompt: give the course name:
      private: false 
  tasks:
  - name: task-1
    ansible.builtin.debug:
      msg: "hi am learning {{COURSE}}, duration is {{VALUE}} months"