- name: ansible
  hosts: localhost
  become: true 
  vars: 
    COURSE: "devops" # string
    Tools: # list
    - linux
    - terraform
    - ansible
    Experience: # map or dictionary
      devops: 3
      aws: 2
      docker: 1
    RealProject: true #boolean
  tasks:
  - name: printing the contents
    ansible.builtin.debug:
      msg: "{{COURSE}},{{Tools}},{{Experience}},{{RealProject}}"

