- name: ansible
  hosts: localhost
  become: true
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: user 
    ignore_errors: true

  - name: printing user information
    ansible.builtin.debug:
      msg: "user info: {{user}}"
       
  - name: creating a user
    ansible.builtin.command: useradd expense
    when: user.rc !=0