- name: ansible
  hosts: localhost
  become: true
  tasks:
  - name: task-1
    ansible.builtin.command: id expense
    ignore_errors: true
    register: {{id expense}} 
  # - name: task-2
  #   ansible.builtin.command: useradd expense
  #   when 