- name: functions
  hosts: localhost
  become: true
  vars: 
  tasks:
  - name: task-1
    ansible.builtin.debug:
      msg: "hi am learning {{ course | default('Ansible') }} "
  - name: task-2
    vars: 
      numbers: [ 21,22,23,23,24,25 ]
    ansible.builtin.debug:
      msg: "priniting the numbers{{ numbers | unique }}"
  - name: task-3
    vars:
      msg: hi this is swaroop
    ansible.builtin.debug:
      msg: "{{ msg | upper }}"
  - name: task-3
    vars:
      msg: hi this is SWAROOP 
    ansible.builtin.debug:
      msg: "{{ msg | lower }}"
  - name: task-4
    vars:
      my_dict:
        COURSE: "devops"
        TRAINER: "shiva"
        DURATION: "120hrs"
    ansible.builtin.debug:
      msg: "am learning {{ my_dict | dict2items }}"
      