- name: installing nodejs
  hosts: backend
  become: true
  tasks:
  - name: disabling nodejs 20
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enabling nodejs20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs 
    ansible.builtin.dnf:
      name: nodejs
      state: latest

  - name: creating a user 
    ansible.builtin.user:
      name: expense 

  - name: Create a directory 
    ansible.builtin.file:
      path: /app
      state: directory

  - name: downloading and unzipping backend file 
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /app
      remote_src: yes

  # - name: downloading dependencies
  #   ansible.builtin.command: npm install 
  #   args:
  #     chdir: /app      