- name: configuring db server 
  hosts: db
  become: true
  vars:
    mysql_root_password: ExpenseApp@1
  tasks:
  - name: installing mysql server
    ansible.builtin.dnf: 
      name: mysql-server
      state: latest

  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true

  - name: Make sure pymysql is present
    pip:
      name: pymysql
      state: present

  - name: installing packages
    ansible.builtin.pip:
      name: cryptography
      state: latest 

  - name: checking mysql credentials
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: db.masterdevops.store
    ignore_errors: true
    register: mysql_passwordcheck

  - name: print ouput
    ansible.builtin.debug:
      msg: "output: {{mysql_passwordcheck}}"

  - name: setting the root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass {{mysql_root_password}}
    when: mysql_passwordcheck.failed is true 