- name: configuring frontend server
  hosts: frontend
  become: true
  tasks:
  - name: installing nginx 
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: starting and enabling nginx server
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: Remove the default contents in html file
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: creating the html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: downloading and unzipping frontend file 
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  
  - name: setting up the systemd services
    ansible.builtin.copy:
      src: expense.conf 
      dest: vim /etc/nginx/default.d/expense.conf

  - name: restart nginx
    ansible.builin.service:
      name: nginx
      state: restarted    